### PR TITLE
Feature checkpoint5

### PR DESCRIPTION
**Pull request by CharlesHDoubler**

### CODE REVIEW

**Comment by kddrake** [comment]
@CharlesHDoubler sorry for asking so late, but would you mind updating your key?

**Comment by CharlesHDoubler** [comment]
What exactly do you mean by that? Thank you
________________________________

**Comment by kddrake** [comment]
@CharlesHDoubler your [API key](https://github.com/MissouriState-CSC515-Spring2020/charleshdoubler-project/pull/8/files#diff-d78b38bfdf1fa93663fde078230596ddR19) is no longer valid, and thus, your calls to the Youtube API are failing. You'd just need to get an updated key from Youtube (I imagine in the same way you got one initially) and push the updated key to this branch.

**Comment by CharlesHDoubler** [comment]
Thank you for the update, I will do so and update it later today!
________________________________

**Pull request merged**
